=== bbalage/N5IF3Vxmlgyak/N5IF3V_20201008/ember.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="emberek">
    <xs:complexType>
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="ember" type="embertype"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
    <xs:complexType name="embertype">
        <xs:sequence>
            <xs:element name="nev1" type="xs:string"/>
            <xs:element name="fizetes" type="xs:int"/>
            <xs:element name="nev" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== bbalage/N5IF3Vxmlgyak/N5IF3V_20201008/ember.xml
<?xml version="1.0" encoding="UTF-8" ?>
<emberek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ember.xsd">
    <ember>
        <nev1>Bolyki</nev1>
        <fizetes>600000</fizetes>
        <nev>Balázs</nev>
    </ember>
    <ember>
        <nev1>Hunyadi</nev1>
        <fizetes>1000000</fizetes>
        <nev>Mátyás</nev>
    </ember>
</emberek>
